<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="rEMODEL"
    nsURI="http://www.mydreamy.net/requirementmodel/REMODEL"
    nsPrefix="rEMODEL">
  <eClassifiers
      xsi:type="ecore:EClass"
      name="RequirementModel">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="description"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="UseCaseModel"
        eType="#//UseCaseModel"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="DomainModel"
        eType="#//DomainModel"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="DomainModel">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="label"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="entity"
        upperBound="-1"
        eType="#//Entity"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Entity">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="isCRUD"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="superEntity"
        eType="#//Entity"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="description"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="attributes"
        upperBound="-1"
        eType="#//Attribute"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="reference"
        upperBound="-1"
        eType="#//Reference"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="invariance"
        upperBound="-1"
        eType="#//Invariance"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Attribute">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="type"
        eType="#//TypeCS"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="ismultiple"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Reference">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="entity"
        eType="#//Entity"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="ismultiple"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="isReverseAssoication"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="isAggregation"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="isComposition"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="type"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="UseCaseModel">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="label"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="uc"
        upperBound="-1"
        eType="#//UC"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="actor"
        upperBound="-1"
        eType="#//Actor"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="interaction"
        upperBound="-1"
        eType="#//Interaction"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="service"
        upperBound="-1"
        eType="#//Service"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="contract"
        upperBound="-1"
        eType="#//Contract"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Actor"
      eSuperTypes="#//Participant">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="label"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="superActor"
        eType="#//Actor"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="uc"
        unique="false"
        upperBound="-1"
        eType="#//UC"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="UC">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="label"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="UCRelation"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="relateduc"
        unique="false"
        upperBound="-1"
        eType="#//UC"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="ssd"
        unique="false"
        upperBound="-1"
        eType="#//Interaction"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="service"
        unique="false"
        upperBound="-1"
        eType="#//Service"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="description"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="EntityType"
      eSuperTypes="#//TypeCS">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="entity"
        eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Interaction">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="participants"
        unique="false"
        upperBound="-1"
        eType="#//Participant"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="messages"
        upperBound="-1"
        eType="#//Message"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="executions"
        upperBound="-1"
        eType="#//Execution"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="combinedFragments"
        upperBound="-1"
        eType="#//CombinedFragment"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="ends"
        upperBound="-1"
        eType="#//AbstractEnd"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Message">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="sendingEnd"
        eType="#//MixEnd"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="receivingEnd"
        eType="#//MixEnd"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="CallMessage"
      eSuperTypes="#//Message">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="op"
        eType="#//Operation"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="ReturnMessage"
      eSuperTypes="#//Message">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="invocationMessage"
        eType="#//Message"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Execution"
      eSuperTypes="#//MultiEnd">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="owner"
        eType="#//Participant"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="start"
        eType="#//ExecutionEnd"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="end"
        eType="#//ExecutionEnd"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="CombinedFragment">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="operator"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="coveredParticipants"
        unique="false"
        upperBound="-1"
        eType="#//Participant"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="start"
        eType="#//CombinedFragmentEnd"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="finish"
        eType="#//CombinedFragmentEnd"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="ownedOperands"
        upperBound="-1"
        eType="#//Operand"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Operand">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="start"
        eType="#//OperandEnd"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="finish"
        eType="#//MixOpAndCFEnd"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="AbstractEnd">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="MixEnd"
      eSuperTypes="#//AbstractEnd">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="context"
        eType="#//MultiEnd"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="MixOpAndCFEnd"
      eSuperTypes="#//AbstractEnd"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="MessageEnd"
      eSuperTypes="#//MixEnd">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="message"
        eType="#//Message"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="MultiEnd">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="ExecutionEnd"
      eSuperTypes="#//MixEnd">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="execution"
        eType="#//Execution"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="CombinedFragmentEnd"
      eSuperTypes="#//MixOpAndCFEnd">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="owner"
        eType="#//CombinedFragment"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="OperandEnd"
      eSuperTypes="#//MixOpAndCFEnd">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="owner"
        eType="#//Operand"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Service"
      eSuperTypes="#//Participant">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="operation"
        upperBound="-1"
        eType="#//Operation"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="temp_property"
        upperBound="-1"
        eType="#//Attribute"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="workflow"
        unique="false"
        upperBound="-1"
        eType="#//Workflow"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="invariance"
        upperBound="-1"
        eType="#//Invariance"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Participant"
      eSuperTypes="#//MultiEnd">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="description"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Workflow">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="participants"
        unique="false"
        upperBound="-1"
        eType="#//Participant"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="partitions"
        upperBound="-1"
        eType="#//Partition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Partition">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="name"
        eType="#//Participant"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="exps"
        upperBound="-1"
        eType="#//WorkflowExp"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="WorkflowExp"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="PartitionAction"
      eSuperTypes="#//WorkflowExp">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="patition"
        eType="#//Participant"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="action"
        eType="#//JoinExp"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="JoinExp"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="ActivityFinal"
      eSuperTypes="#//WorkflowExp">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="InitalNode"
      eSuperTypes="#//WorkflowExp">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="ForkNode"
      eSuperTypes="#//WorkflowExp">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="startlinks"
        unique="false"
        upperBound="-1"
        eType="#//JoinExp"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="JoinNode"
      eSuperTypes="#//WorkflowExp">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="endlinks"
        unique="false"
        upperBound="-1"
        eType="#//JoinExp"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="ComplexOpeartion"
      eSuperTypes="#//WorkflowExp"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="SimpleOperation"
      eSuperTypes="#//WorkflowExp">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="ref"
        eType="#//Operation"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="LoopExp"
      eSuperTypes="#//JoinExp #//ComplexOpeartion">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="exps"
        upperBound="-1"
        eType="#//WorkflowExp"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="SwitchExp"
      eSuperTypes="#//JoinExp #//ComplexOpeartion">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="cases"
        upperBound="-1"
        eType="#//SwitchCase"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="default"
        eType="#//SwitchDefault"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="SwitchCase">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="caseValue"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="op"
        eType="#//SimpleOperation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="SwitchDefault">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="op"
        eType="#//SimpleOperation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Operation"
      eSuperTypes="#//JoinExp">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="parameter"
        upperBound="-1"
        eType="#//Parameter"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="returnType"
        eType="#//TypeCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Parameter">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="type"
        eType="#//TypeCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="TypeCS"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Invariance">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="ocl"
        eType="#//OCLExpressionCS"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="isForAssociation"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="EnumEntity"
      eSuperTypes="#//TypeCS">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="element"
        upperBound="-1"
        eType="#//EnumItem"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="EnumItem">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Contract">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="service"
        eType="#//Service"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="op"
        eType="#//Operation"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="def"
        eType="#//Definition"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="pre"
        eType="#//Precondition"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="post"
        eType="#//Postcondition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Definition">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="variable"
        upperBound="-1"
        eType="#//VariableDeclarationCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Precondition">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="oclexp"
        eType="#//OCLExpressionCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Postcondition">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="oclexp"
        eType="#//OCLExpressionCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="OCLExpressionCS"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="NestedExpCS"
      eSuperTypes="#//OCLExpressionCS">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="nestedExpression"
        eType="#//OCLExpressionCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="LogicFormulaExpCS"
      eSuperTypes="#//OCLExpressionCS">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="atomicexp"
        upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="connector"
        unique="false"
        upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="AtomicExpression">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="leftside"
        eType="#//LeftSubAtomicExpression"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="infixop"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="rightside"
        eType="#//RightSubAtomicExpression"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="op"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="num"
        eType="#//PrimitiveLiteralExpCS"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="exp"
        eType="#//AtomicExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="LeftSubAtomicExpression"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="RightSubAtomicExpression"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="CallExpCS"
      eSuperTypes="#//LeftSubAtomicExpression #//RightSubAtomicExpression"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="LoopExpCS"
      eSuperTypes="#//CallExpCS"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="IteratorExpCS"
      eSuperTypes="#//LoopExpCS">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="objectCall"
        eType="#//FeatureCallExpCS"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="simpleCall"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="iterator"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="varibles"
        upperBound="-1"
        eType="#//VariableDeclarationCS"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="exp"
        eType="#//OCLExpressionCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="EntityAttributeName">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="ArgumentsCS">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="first"
        eType="#//OCLExpressionCS"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="next"
        eType="#//ArgumentsCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="FeatureCallExpCS"
      eSuperTypes="#//CallExpCS"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="StandardNavigationCallExpCS"
      eSuperTypes="#//FeatureCallExpCS">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="classifercall"
        eType="#//ClassiferCallExpCS"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="propertycall"
        eType="#//PropertyCallExpCS"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="object"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="navop"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="standardOP"
        eType="#//StandardCollectionOperation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="StandardOperationExpCS"
      eSuperTypes="#//FeatureCallExpCS">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="object"
        eType="#//VariableExpCS"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="property"
        eType="#//VariableExpCS"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="premark"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="predefinedop"
        eType="#//PredefineOp"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="PredefineOp">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="StandardNoneParameterOperation"
      eSuperTypes="#//PredefineOp"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="StandardParameterOperation"
      eSuperTypes="#//PredefineOp">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="type"
        eType="#//TypeCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="StandardCollectionOperation">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="object"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="StandardDateOperation"
      eSuperTypes="#//PredefineOp">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="object"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="datenum"
        eType="#//NumberLiteralExpCS"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="procall"
        eType="#//PropertyCallExpCS"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="nested"
        eType="#//StandardDateOperation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="ClassiferCallExpCS"
      eSuperTypes="#//FeatureCallExpCS">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="entity"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="op"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="PropertyCallExpCS"
      eSuperTypes="#//FeatureCallExpCS">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="name"
        eType="#//VariableExpCS"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="selfproperty"
        eType="#//VariableExpCS"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="attribute"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="premark"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="OperationCallExpCS"
      eSuperTypes="#//FeatureCallExpCS">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="parameters"
        upperBound="-1"
        eType="#//OperationParameters"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="OperationParameters">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="object"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="objectproperty"
        eType="#//PropertyCallExpCS"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="string"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="VariableExpCS"
      eSuperTypes="#//LeftSubAtomicExpression #//RightSubAtomicExpression">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="symbol"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="IfExpCS"
      eSuperTypes="#//OCLExpressionCS">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="condition"
        eType="#//OCLExpressionCS"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="thenExpression"
        eType="#//OCLExpressionCS"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="elseExpression"
        eType="#//OCLExpressionCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="LetExpCS"
      eSuperTypes="#//OCLExpressionCS">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="variable"
        upperBound="-1"
        eType="#//VariableDeclarationCS"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="inExpression"
        eType="#//OCLExpressionCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="VariableDeclarationCS">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="type"
        eType="#//TypeCS"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="initExpression"
        eType="#//OCLExpressionCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="LiteralExpCS"
      eSuperTypes="#//OCLExpressionCS #//RightSubAtomicExpression"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="EnumLiteralExpCS"
      eSuperTypes="#//LiteralExpCS">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="enumname"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="eunmitem"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="TupleLiteralExpCS"
      eSuperTypes="#//LiteralExpCS">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="variables"
        upperBound="-1"
        eType="#//VariableDeclarationCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="TupleTypeCS">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="variables"
        upperBound="-1"
        eType="#//VariableDeclarationCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="CollectionTypeCS"
      eSuperTypes="#//TypeCS">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="name"
        eType="#//CollectionTypeIdentifierCS"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="type"
        eType="#//TypeCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="CollectionLiteralExpCS"
      eSuperTypes="#//LiteralExpCS">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="kind"
        eType="#//CollectionTypeIdentifierCS"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="part"
        upperBound="-1"
        eType="#//CollectionLiteralPartCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="CollectionLiteralPartCS"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="CollectionRangeCS"
      eSuperTypes="#//CollectionLiteralPartCS">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="first"
        eType="#//OCLExpressionCS"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="last"
        eType="#//OCLExpressionCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="CollectionItem"
      eSuperTypes="#//CollectionLiteralPartCS">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="item"
        eType="#//OCLExpressionCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="PrimitiveLiteralExpCS"
      eSuperTypes="#//LiteralExpCS">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="symbol"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="NumberLiteralExpCS"
      eSuperTypes="#//PrimitiveLiteralExpCS"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="BooleanLiteralExpCS"
      eSuperTypes="#//PrimitiveLiteralExpCS"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="StringLiteralExpCS"
      eSuperTypes="#//PrimitiveLiteralExpCS"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="NullLiteralExpCS"
      eSuperTypes="#//PrimitiveLiteralExpCS"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="InvalidLiteralExpCS"
      eSuperTypes="#//PrimitiveLiteralExpCS"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="ReservedKeywordCS">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="CollectionTypeIdentifierCS"
      eSuperTypes="#//ReservedKeywordCS"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="PrimitiveTypeCS"
      eSuperTypes="#//TypeCS #//ReservedKeywordCS"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="OclTypeCS"
      eSuperTypes="#//ReservedKeywordCS"/>
</ecore:EPackage>
